#!/bin/bash

cp -rf $HOME/MacUSB/OpenCore/Update/EFI             $HOME/MacUSB/OpenCore/Series-9/
cp -rf $HOME/MacUSB/OpenCore/Update/EFI             $HOME/MacUSB/OpenCore/Series-100/
cp -rf $HOME/MacUSB/OpenCore/Update/EFI             $HOME/MacUSB/OpenCore/Series-200/

cp -rf $HOME/MacUSB/Kexts/AirportBrcmFixup.kext     $HOME/MacUSB/OpenCore/Series-9/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/AppleALC.kext             $HOME/MacUSB/OpenCore/Series-9/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/AtherosE2200Ethernet.kext $HOME/MacUSB/OpenCore/Series-9/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/IntelMausi.kext           $HOME/MacUSB/OpenCore/Series-9/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/Lilu.kext                 $HOME/MacUSB/OpenCore/Series-9/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/RealtekRTL8111.kext       $HOME/MacUSB/OpenCore/Series-9/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/RestrictEvents.kext       $HOME/MacUSB/OpenCore/Series-9/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/VirtualSMC.kext           $HOME/MacUSB/OpenCore/Series-9/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/WhateverGreen.kext        $HOME/MacUSB/OpenCore/Series-9/EFI/OC/Kexts/

cp -rf $HOME/MacUSB/Kexts/AirportBrcmFixup.kext     $HOME/MacUSB/OpenCore/Series-100/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/AppleALC.kext             $HOME/MacUSB/OpenCore/Series-100/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/AtherosE2200Ethernet.kext $HOME/MacUSB/OpenCore/Series-100/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/IntelMausi.kext           $HOME/MacUSB/OpenCore/Series-100/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/Lilu.kext                 $HOME/MacUSB/OpenCore/Series-100/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/RealtekRTL8111.kext       $HOME/MacUSB/OpenCore/Series-100/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/RestrictEvents.kext       $HOME/MacUSB/OpenCore/Series-100/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/VirtualSMC.kext           $HOME/MacUSB/OpenCore/Series-100/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/WhateverGreen.kext        $HOME/MacUSB/OpenCore/Series-100/EFI/OC/Kexts/

cp -rf $HOME/MacUSB/Kexts/AirportBrcmFixup.kext     $HOME/MacUSB/OpenCore/Series-200/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/AppleALC.kext             $HOME/MacUSB/OpenCore/Series-200/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/AtherosE2200Ethernet.kext $HOME/MacUSB/OpenCore/Series-200/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/IntelMausi.kext           $HOME/MacUSB/OpenCore/Series-200/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/Lilu.kext                 $HOME/MacUSB/OpenCore/Series-200/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/RealtekRTL8111.kext       $HOME/MacUSB/OpenCore/Series-200/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/RestrictEvents.kext       $HOME/MacUSB/OpenCore/Series-200/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/VirtualSMC.kext           $HOME/MacUSB/OpenCore/Series-200/EFI/OC/Kexts/
cp -rf $HOME/MacUSB/Kexts/WhateverGreen.kext        $HOME/MacUSB/OpenCore/Series-200/EFI/OC/Kexts/
