#!/bin/bash

cp -rf OpenCore/Update/EFI OpenCore/Series-9/
cp -rf OpenCore/Update/EFI OpenCore/Series-100/
cp -rf OpenCore/Update/EFI OpenCore/Series-200/

cp -rf Kexts/AirportBrcmFixup.kext OpenCore/Series-9/EFI/OC/Kexts/
cp -rf Kexts/AppleALC.kext OpenCore/Series-9/EFI/OC/Kexts/
cp -rf Kexts/AtherosE2200Ethernet.kext OpenCore/Series-9/EFI/OC/Kexts/
cp -rf Kexts/IntelMausi.kext OpenCore/Series-9/EFI/OC/Kexts/
cp -rf Kexts/Lilu.kext OpenCore/Series-9/EFI/OC/Kexts/
cp -rf Kexts/RealtekRTL8111.kext OpenCore/Series-9/EFI/OC/Kexts/
cp -rf Kexts/RestrictEvents.kext OpenCore/Series-9/EFI/OC/Kexts/
cp -rf Kexts/VirtualSMC.kext OpenCore/Series-9/EFI/OC/Kexts/
cp -rf Kexts/WhateverGreen.kext OpenCore/Series-9/EFI/OC/Kexts/

cp -rf Kexts/AirportBrcmFixup.kext OpenCore/Series-100/EFI/OC/Kexts/
cp -rf Kexts/AppleALC.kext OpenCore/Series-100/EFI/OC/Kexts/
cp -rf Kexts/AtherosE2200Ethernet.kext OpenCore/Series-100/EFI/OC/Kexts/
cp -rf Kexts/IntelMausi.kext OpenCore/Series-100/EFI/OC/Kexts/
cp -rf Kexts/Lilu.kext OpenCore/Series-100/EFI/OC/Kexts/
cp -rf Kexts/RealtekRTL8111.kext OpenCore/Series-100/EFI/OC/Kexts/
cp -rf Kexts/RestrictEvents.kext OpenCore/Series-100/EFI/OC/Kexts/
cp -rf Kexts/VirtualSMC.kext OpenCore/Series-100/EFI/OC/Kexts/
cp -rf Kexts/WhateverGreen.kext OpenCore/Series-100/EFI/OC/Kexts/

cp -rf Kexts/AirportBrcmFixup.kext OpenCore/Series-200/EFI/OC/Kexts/
cp -rf Kexts/AppleALC.kext OpenCore/Series-200/EFI/OC/Kexts/
cp -rf Kexts/AtherosE2200Ethernet.kext OpenCore/Series-200/EFI/OC/Kexts/
cp -rf Kexts/IntelMausi.kext OpenCore/Series-200/EFI/OC/Kexts/
cp -rf Kexts/Lilu.kext OpenCore/Series-200/EFI/OC/Kexts/
cp -rf Kexts/RealtekRTL8111.kext OpenCore/Series-200/EFI/OC/Kexts/
cp -rf Kexts/RestrictEvents.kext OpenCore/Series-200/EFI/OC/Kexts/
cp -rf Kexts/VirtualSMC.kext OpenCore/Series-200/EFI/OC/Kexts/
cp -rf Kexts/WhateverGreen.kext OpenCore/Series-200/EFI/OC/Kexts/
