#!/bin/bash

E1="EFI-OpenCore-Series-9.zip"
E2="EFI-OpenCore-Series-100-200.zip"
E3="EFI-OpenCore-Series-300-400.zip"
E4="EFI-OpenCore-Series-500.zip"

F1="Series-9"
F2="Series-100"
F3="Series-200"
F4="Series-300"
F5="Series-400"
F6="Series-500"

echo "Removing Folders..."
rm -rf "Clover-DSDT"
rm -rf "Clover-Theme"
rm -rf "OpenCore-EFI"
rm -rf "OpenCore"
rm -rf "Temp"
rm -rf "Tools"
rm -f  "README.md"

echo "Creating Folders..."
mkdir -p "OpenCore/$F1"
mkdir -p "OpenCore/$F2"
mkdir -p "OpenCore/$F3"
mkdir -p "OpenCore/$F4"
mkdir -p "OpenCore/$F5"
mkdir -p "OpenCore/$F6"
mkdir -p "Temp/$F1"
mkdir -p "Temp/$F2"
mkdir -p "Temp/$F3"
mkdir -p "Temp/$F4"
mkdir -p "Temp/$F5"
mkdir -p "Temp/$F6"
mkdir -p "Tools"

echo "Downloading Files..."
wget -q -P "Temp/" "https://github.com/CrazyTeeka/MacUSB/blob/master/OpenCore-EFI/$E1?raw=true"
wget -q -P "Temp/" "https://github.com/CrazyTeeka/MacUSB/blob/master/OpenCore-EFI/$E2?raw=true"
wget -q -P "Temp/" "https://github.com/CrazyTeeka/MacUSB/blob/master/OpenCore-EFI/$E3?raw=true"
wget -q -P "Temp/" "https://github.com/CrazyTeeka/MacUSB/blob/master/OpenCore-EFI/$E4?raw=true"
wget -q -P "Temp/" "https://github.com/CrazyTeeka/MacUSB/blob/master/OpenCore/OpenCore-Configurator.zip?raw=true"
wget -q -P "Temp/" "https://github.com/CrazyTeeka/MacUSB/blob/master/Tools/AppCleaner.zip?raw=true"

echo "Unpacking Files..."
unzip -o -qq "Temp/$E1?raw=true" -d "Temp/$F1/"
unzip -o -qq "Temp/$E2?raw=true" -d "Temp/$F2/"
unzip -o -qq "Temp/$E2?raw=true" -d "Temp/$F3/"
unzip -o -qq "Temp/$E3?raw=true" -d "Temp/$F4/"
unzip -o -qq "Temp/$E3?raw=true" -d "Temp/$F5/"
unzip -o -qq "Temp/$E4?raw=true" -d "Temp/$F6/"

echo "Copying Files..."
cp -rf "Temp/$F1/EFI" "OpenCore/$F1/"
cp -rf "Temp/$F2/EFI" "OpenCore/$F2/"
cp -rf "Temp/$F3/EFI" "OpenCore/$F3/"
cp -rf "Temp/$F4/EFI" "OpenCore/$F4/"
cp -rf "Temp/$F5/EFI" "OpenCore/$F5/"
cp -rf "Temp/$F6/EFI" "OpenCore/$F6/"
cp -f  "Temp/AppCleaner.zip?raw=true"            "Tools/AppCleaner.zip"
cp -f  "Temp/OpenCore-Configurator.zip?raw=true" "Tools/OpenCore-Configurator.zip"

echo "OpenCore Config..."
sed -i '11 s/<string>Full Olarila Solution<\/string>/<string>DSDT<\/string>/g'   "OpenCore/$F1/EFI/OC/config.plist"
sed -i '11 s/<string>Real Full Solution<\/string>/<string>DSDT<\/string>/g'      "OpenCore/$F2/EFI/OC/config.plist"
sed -i '11 s/<string>Real Full Solution<\/string>/<string>DSDT<\/string>/g'      "OpenCore/$F3/EFI/OC/config.plist"
sed -i '11 s/<string>Real Full Solution<\/string>/<string>DSDT<\/string>/g'      "OpenCore/$F4/EFI/OC/config.plist"
sed -i '11 s/<string>Real Full Solution<\/string>/<string>DSDT<\/string>/g'      "OpenCore/$F5/EFI/OC/config.plist"
sed -i '11 s/<string>Real Full Solution<\/string>/<string>DSDT<\/string>/g'      "OpenCore/$F6/EFI/OC/config.plist"
sed -i '19 s/<string><\/string>/<string>SSDT Device EC<\/string>/g'              "OpenCore/$F1/EFI/OC/config.plist"
sed -i '36 s/<string>RTC _STA<\/string>/<string>Fix RTC Bug<\/string>/g'         "OpenCore/$F1/EFI/OC/config.plist"
sed -i '44 s/<string>Fix RTC _STA bug<\/string>/<string>Fix RTC Bug<\/string>/g' "OpenCore/$F2/EFI/OC/config.plist"
sed -i '44 s/<string>Fix RTC _STA bug<\/string>/<string>Fix RTC Bug<\/string>/g' "OpenCore/$F3/EFI/OC/config.plist"
sed -i '44 s/<string>Fix RTC _STA bug<\/string>/<string>Fix RTC Bug<\/string>/g' "OpenCore/$F4/EFI/OC/config.plist"
sed -i '44 s/<string>Fix RTC _STA bug<\/string>/<string>Fix RTC Bug<\/string>/g' "OpenCore/$F5/EFI/OC/config.plist"
sed -i '44 s/<string>Fix RTC _STA bug<\/string>/<string>Fix RTC Bug<\/string>/g' "OpenCore/$F6/EFI/OC/config.plist"
sed -i '27 s/<string>SSDT ThundetBolt HotPlug<\/string>/<string>SSDT ThunderBolt HotPlug<\/string>/g' "OpenCore/$F2/EFI/OC/config.plist"
sed -i '27 s/<string>SSDT ThundetBolt HotPlug<\/string>/<string>SSDT ThunderBolt HotPlug<\/string>/g' "OpenCore/$F3/EFI/OC/config.plist"
sed -i '27 s/<string>SSDT ThundetBolt HotPlug<\/string>/<string>SSDT ThunderBolt HotPlug<\/string>/g' "OpenCore/$F4/EFI/OC/config.plist"
sed -i '27 s/<string>SSDT ThundetBolt HotPlug<\/string>/<string>SSDT ThunderBolt HotPlug<\/string>/g' "OpenCore/$F5/EFI/OC/config.plist"
sed -i '27 s/<string>SSDT ThundetBolt HotPlug<\/string>/<string>SSDT ThunderBolt HotPlug<\/string>/g' "OpenCore/$F6/EFI/OC/config.plist"

echo "Cleaning Up..."
rm -rf "Temp"

echo "Done"
