#!/bin/bash

C1="EFI-Clover-Series-9.zip"

CF1="Series-9"

OC1="EFI-OpenCore-Series-9.zip"
OC2="EFI-OpenCore-Series-100-200.zip"
OC3="EFI-OpenCore-Series-300-400.zip"
OC4="EFI-OpenCore-Series-500.zip"

OCF1="Series-9"
OCF2="Series-100"
OCF3="Series-200"
OCF4="Series-300"
OCF5="Series-400"
OCF6="Series-500"

echo "Removing Folders..."
rm -rf "Clover-DSDT"
rm -rf "Clover-EFI"
rm -rf "Clover"
rm -rf "OpenCore-EFI"
rm -rf "OpenCore"
rm -rf "Temp"
rm -rf "Tools"
rm -f  "README.md"

echo "Creating Folders..."
mkdir -p "Clover/$CF1"
mkdir -p "OpenCore/$OCF1"
mkdir -p "OpenCore/$OCF2"
mkdir -p "OpenCore/$OCF3"
mkdir -p "OpenCore/$OCF4"
mkdir -p "OpenCore/$OCF5"
mkdir -p "OpenCore/$OCF6"
mkdir -p "Temp/Clover-$CF1"
mkdir -p "Temp/OpenCore-$OCF1"
mkdir -p "Temp/OpenCore-$OCF2"
mkdir -p "Temp/OpenCore-$OCF3"
mkdir -p "Temp/OpenCore-$OCF4"
mkdir -p "Temp/OpenCore-$OCF5"
mkdir -p "Temp/OpenCore-$OCF6"
mkdir -p "Tools"

echo "Downloading Files..."
wget -q -P "Temp/" "https://github.com/CrazyTeeka/MacUSB/raw/master/Clover-EFI/$C1"
wget -q -P "Temp/" "https://github.com/CrazyTeeka/MacUSB/raw/master/Clover-EFI/Theme-Clovy.zip"
wget -q -P "Temp/" "https://github.com/CrazyTeeka/MacUSB/raw/master/OpenCore-EFI/$OC1"
wget -q -P "Temp/" "https://github.com/CrazyTeeka/MacUSB/raw/master/OpenCore-EFI/$OC2"
wget -q -P "Temp/" "https://github.com/CrazyTeeka/MacUSB/raw/master/OpenCore-EFI/$OC3"
wget -q -P "Temp/" "https://github.com/CrazyTeeka/MacUSB/raw/master/OpenCore-EFI/$OC4"
wget -q -P "Temp/" "https://github.com/CrazyTeeka/MacUSB/raw/master/OpenCore/HfsPlus.efi"
wget -q -P "Temp/" "https://github.com/CrazyTeeka/MacUSB/raw/master/OpenCore/OpenCore-Configurator.zip"
wget -q -P "Temp/" "https://github.com/CrazyTeeka/MacUSB/raw/master/Tools/AppCleaner.zip"

echo "Unpacking Files..."
unzip -o -qq "Temp/$C1"  -d "Temp/Clover-$CF1/"
unzip -o -qq "Temp/$OC1" -d "Temp/OpenCore-$OCF1/"
unzip -o -qq "Temp/$OC2" -d "Temp/OpenCore-$OCF2/"
unzip -o -qq "Temp/$OC2" -d "Temp/OpenCore-$OCF3/"
unzip -o -qq "Temp/$OC3" -d "Temp/OpenCore-$OCF4/"
unzip -o -qq "Temp/$OC3" -d "Temp/OpenCore-$OCF5/"
unzip -o -qq "Temp/$OC4" -d "Temp/OpenCore-$OCF6/"
unzip -o -qq "Temp/Theme-Clovy.zip" -d "Temp/"

echo "Copying Files..."
cp -rf "Temp/Clover-$CF1/EFI" "Clover/$CF1/"
cp -rf "Temp/Clovy" "Clover/$CF1/EFI/CLOVER/themes/"
cp -rf "Temp/OpenCore-$OCF1/EFI" "OpenCore/$OCF1/"
cp -rf "Temp/OpenCore-$OCF2/EFI" "OpenCore/$OCF2/"
cp -rf "Temp/OpenCore-$OCF3/EFI" "OpenCore/$OCF3/"
cp -rf "Temp/OpenCore-$OCF4/EFI" "OpenCore/$OCF4/"
cp -rf "Temp/OpenCore-$OCF5/EFI" "OpenCore/$OCF5/"
cp -rf "Temp/OpenCore-$OCF6/EFI" "OpenCore/$OCF6/"
cp -f  "Temp/HfsPlus.efi" "Clover/"
cp -f  "Temp/HfsPlus.efi" "OpenCore/"
cp -f  "Temp/AppCleaner.zip" "Tools/"
cp -f  "Temp/OpenCore-Configurator.zip" "Tools/"

echo "Clover Cleanup..."
rm -rf "Clover/Series-9/EFI/CLOVER/drivers/BIOS"
rm -rf "Clover/Series-9/EFI/CLOVER/misc"
rm -rf "Clover/Series-9/EFI/CLOVER/themes/Olarila"
cp -f  "Clover/HfsPlus.efi" "Clover/Series-9/EFI/CLOVER/drivers/UEFI/HfsPlus.efi"
sed -i '100 s/<string>_STA RTC<\/string>/<string>Fix RTC Bug<\/string>/g' "Clover/$CF1/EFI/CLOVER/config.plist"
sed -i '198 s/<integer>5<\/integer>/<integer>10<\/integer>/g' "Clover/$CF1/EFI/CLOVER/config.plist"
sed -i '573 s/<string>Olarila<\/string>/<string>Clovy<\/string>/g' "Clover/$CF1/EFI/CLOVER/config.plist"
sed -i '787 s/<string>USB port limit patch #1 10.14.x modify by DalianSky(credit ydeng)<\/string>/<string>USB Port Limit Patch #1 (10.14)<\/string>/g' "Clover/$CF1/EFI/CLOVER/config.plist"
sed -i '803 s/<string>USB port limit patch #2 10.14.x modify by DalianSky(credit PMHeart)<\/string>/<string>USB Port Limit Patch #2 (10.14)<\/string>/g' "Clover/$CF1/EFI/CLOVER/config.plist"
sed -i '819 s/<string>USB Port limit patch #3 10.14.x modify by DalianSky(credits PMheart)<\/string>/<string>USB Port Limit Patch #3 (10.14)<\/string>/g' "Clover/$CF1/EFI/CLOVER/config.plist"
sed -i '835 s/<string>USB Port limit patch #4 10.14.x modify by DalianSky(credits PMheart)<\/string>/<string>USB Port Limit Patch #4 (10.14)<\/string>/g' "Clover/$CF1/EFI/CLOVER/config.plist"
sed -i '851 s/<string>USB Port limit patch #1(credits PMheart)<\/string>/<string>USB Port Limit Patch #1 (10.15)<\/string>/g' "Clover/$CF1/EFI/CLOVER/config.plist"
sed -i '867 s/<string>USB Port limit patch #2(credits PMheart)<\/string>/<string>USB Port Limit Patch #2 (10.15)<\/string>/g' "Clover/$CF1/EFI/CLOVER/config.plist"

echo "OpenCore Cleanup..."
rm -f "OpenCore/Series-9/EFI/OC/Drivers/OpenHfsPlus.efi"
rm -f "OpenCore/Series-100/EFI/OC/Drivers/OpenHfsPlus.efi"
rm -f "OpenCore/Series-200/EFI/OC/Drivers/OpenHfsPlus.efi"
rm -f "OpenCore/Series-300/EFI/OC/Drivers/OpenHfsPlus.efi"
rm -f "OpenCore/Series-400/EFI/OC/Drivers/OpenHfsPlus.efi"
rm -f "OpenCore/Series-500/EFI/OC/Drivers/OpenHfsPlus.efi"
cp -f "OpenCore/HfsPlus.efi" "OpenCore/Series-9/EFI/OC/Drivers/HfsPlus.efi"
cp -f "OpenCore/HfsPlus.efi" "OpenCore/Series-100/EFI/OC/Drivers/HfsPlus.efi"
cp -f "OpenCore/HfsPlus.efi" "OpenCore/Series-200/EFI/OC/Drivers/HfsPlus.efi"
cp -f "OpenCore/HfsPlus.efi" "OpenCore/Series-300/EFI/OC/Drivers/HfsPlus.efi"
cp -f "OpenCore/HfsPlus.efi" "OpenCore/Series-400/EFI/OC/Drivers/HfsPlus.efi"
cp -f "OpenCore/HfsPlus.efi" "OpenCore/Series-500/EFI/OC/Drivers/HfsPlus.efi"
sed -i '11 s/<string>Full Olarila Solution<\/string>/<string>DSDT<\/string>/g'   "OpenCore/$OCF1/EFI/OC/config.plist"
sed -i '11 s/<string>Real Full Solution<\/string>/<string>DSDT<\/string>/g'      "OpenCore/$OCF2/EFI/OC/config.plist"
sed -i '11 s/<string>Real Full Solution<\/string>/<string>DSDT<\/string>/g'      "OpenCore/$OCF3/EFI/OC/config.plist"
sed -i '11 s/<string>Real Full Solution<\/string>/<string>DSDT<\/string>/g'      "OpenCore/$OCF4/EFI/OC/config.plist"
sed -i '11 s/<string>Real Full Solution<\/string>/<string>DSDT<\/string>/g'      "OpenCore/$OCF5/EFI/OC/config.plist"
sed -i '11 s/<string>Real Full Solution<\/string>/<string>DSDT<\/string>/g'      "OpenCore/$OCF6/EFI/OC/config.plist"
sed -i '19 s/<string><\/string>/<string>SSDT Device EC<\/string>/g'              "OpenCore/$OCF1/EFI/OC/config.plist"
sed -i '36 s/<string>RTC _STA<\/string>/<string>Fix RTC Bug<\/string>/g'         "OpenCore/$OCF1/EFI/OC/config.plist"
sed -i '44 s/<string>Fix RTC _STA bug<\/string>/<string>Fix RTC Bug<\/string>/g' "OpenCore/$OCF2/EFI/OC/config.plist"
sed -i '44 s/<string>Fix RTC _STA bug<\/string>/<string>Fix RTC Bug<\/string>/g' "OpenCore/$OCF3/EFI/OC/config.plist"
sed -i '44 s/<string>Fix RTC _STA bug<\/string>/<string>Fix RTC Bug<\/string>/g' "OpenCore/$OCF4/EFI/OC/config.plist"
sed -i '44 s/<string>Fix RTC _STA bug<\/string>/<string>Fix RTC Bug<\/string>/g' "OpenCore/$OCF5/EFI/OC/config.plist"
sed -i '44 s/<string>Fix RTC _STA bug<\/string>/<string>Fix RTC Bug<\/string>/g' "OpenCore/$OCF6/EFI/OC/config.plist"
sed -i '836 s/<string>NvmExpressDxe.efi<\/string>/<string>HfsPlus.efi<\/string>/g'    "OpenCore/$OCF1/EFI/OC/config.plist"
sed -i '837 s/<string>OpenCanopy.efi<\/string>/<string>NvmExpressDxe.efi<\/string>/g' "OpenCore/$OCF1/EFI/OC/config.plist"
sed -i '838 s/<string>OpenHfsPlus.efi<\/string>/<string>OpenCanopy.efi<\/string>/g'   "OpenCore/$OCF1/EFI/OC/config.plist"
sed -i '839 s/<string>OpenRuntime.efi<\/string>/<string>OpenRuntime.efi<\/string>/g'  "OpenCore/$OCF1/EFI/OC/config.plist"
sed -i '836 s/<string>NvmExpressDxe.efi<\/string>/<string>HfsPlus.efi<\/string>/g'    "OpenCore/$OCF2/EFI/OC/config.plist"
sed -i '837 s/<string>OpenCanopy.efi<\/string>/<string>NvmExpressDxe.efi<\/string>/g' "OpenCore/$OCF2/EFI/OC/config.plist"
sed -i '838 s/<string>OpenHfsPlus.efi<\/string>/<string>OpenCanopy.efi<\/string>/g'   "OpenCore/$OCF2/EFI/OC/config.plist"
sed -i '839 s/<string>OpenRuntime.efi<\/string>/<string>OpenRuntime.efi<\/string>/g'  "OpenCore/$OCF2/EFI/OC/config.plist"
sed -i '836 s/<string>NvmExpressDxe.efi<\/string>/<string>HfsPlus.efi<\/string>/g'    "OpenCore/$OCF3/EFI/OC/config.plist"
sed -i '837 s/<string>OpenCanopy.efi<\/string>/<string>NvmExpressDxe.efi<\/string>/g' "OpenCore/$OCF3/EFI/OC/config.plist"
sed -i '838 s/<string>OpenHfsPlus.efi<\/string>/<string>OpenCanopy.efi<\/string>/g'   "OpenCore/$OCF3/EFI/OC/config.plist"
sed -i '839 s/<string>OpenRuntime.efi<\/string>/<string>OpenRuntime.efi<\/string>/g'  "OpenCore/$OCF3/EFI/OC/config.plist"
sed -i '836 s/<string>NvmExpressDxe.efi<\/string>/<string>HfsPlus.efi<\/string>/g'    "OpenCore/$OCF4/EFI/OC/config.plist"
sed -i '837 s/<string>OpenCanopy.efi<\/string>/<string>NvmExpressDxe.efi<\/string>/g' "OpenCore/$OCF4/EFI/OC/config.plist"
sed -i '838 s/<string>OpenHfsPlus.efi<\/string>/<string>OpenCanopy.efi<\/string>/g'   "OpenCore/$OCF4/EFI/OC/config.plist"
sed -i '839 s/<string>OpenRuntime.efi<\/string>/<string>OpenRuntime.efi<\/string>/g'  "OpenCore/$OCF4/EFI/OC/config.plist"
sed -i '836 s/<string>NvmExpressDxe.efi<\/string>/<string>HfsPlus.efi<\/string>/g'    "OpenCore/$OCF5/EFI/OC/config.plist"
sed -i '837 s/<string>OpenCanopy.efi<\/string>/<string>NvmExpressDxe.efi<\/string>/g' "OpenCore/$OCF5/EFI/OC/config.plist"
sed -i '838 s/<string>OpenHfsPlus.efi<\/string>/<string>OpenCanopy.efi<\/string>/g'   "OpenCore/$OCF5/EFI/OC/config.plist"
sed -i '839 s/<string>OpenRuntime.efi<\/string>/<string>OpenRuntime.efi<\/string>/g'  "OpenCore/$OCF5/EFI/OC/config.plist"
sed -i '836 s/<string>NvmExpressDxe.efi<\/string>/<string>HfsPlus.efi<\/string>/g'    "OpenCore/$OCF6/EFI/OC/config.plist"
sed -i '837 s/<string>OpenCanopy.efi<\/string>/<string>NvmExpressDxe.efi<\/string>/g' "OpenCore/$OCF6/EFI/OC/config.plist"
sed -i '838 s/<string>OpenHfsPlus.efi<\/string>/<string>OpenCanopy.efi<\/string>/g'   "OpenCore/$OCF6/EFI/OC/config.plist"
sed -i '839 s/<string>OpenRuntime.efi<\/string>/<string>OpenRuntime.efi<\/string>/g'  "OpenCore/$OCF6/EFI/OC/config.plist"
sed -i '27 s/<string>SSDT ThundetBolt HotPlug<\/string>/<string>SSDT ThunderBolt HotPlug<\/string>/g' "OpenCore/$OCF2/EFI/OC/config.plist"
sed -i '27 s/<string>SSDT ThundetBolt HotPlug<\/string>/<string>SSDT ThunderBolt HotPlug<\/string>/g' "OpenCore/$OCF3/EFI/OC/config.plist"
sed -i '27 s/<string>SSDT ThundetBolt HotPlug<\/string>/<string>SSDT ThunderBolt HotPlug<\/string>/g' "OpenCore/$OCF4/EFI/OC/config.plist"
sed -i '27 s/<string>SSDT ThundetBolt HotPlug<\/string>/<string>SSDT ThunderBolt HotPlug<\/string>/g' "OpenCore/$OCF5/EFI/OC/config.plist"
sed -i '27 s/<string>SSDT ThundetBolt HotPlug<\/string>/<string>SSDT ThunderBolt HotPlug<\/string>/g' "OpenCore/$OCF6/EFI/OC/config.plist"

echo "Cleaning Up..."
rm -rf "Temp"

echo "Done"
