#!/bin/bash

if [ -d "OpenCore/Series-9/EFI" ] && [ -d "OpenCore/Update/EFI" ]; then
  cp -f "OpenCore/Update/EFI/BOOT/BOOTx64.efi"               "OpenCore/Series-9/EFI/BOOT/BOOTx64.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/CrScreenshotDxe.efi" "OpenCore/Series-9/EFI/OC/Drivers/CrScreenshotDxe.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/NvmExpressDxe.efi"   "OpenCore/Series-9/EFI/OC/Drivers/NvmExpressDxe.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/OpenCanopy.efi"      "OpenCore/Series-9/EFI/OC/Drivers/OpenCanopy.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/OpenRuntime.efi"     "OpenCore/Series-9/EFI/OC/Drivers/OpenRuntime.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/BootKicker.efi"        "OpenCore/Series-9/EFI/OC/Tools/BootKicker.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ChipTune.efi"          "OpenCore/Series-9/EFI/OC/Tools/ChipTune.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/CleanNvram.efi"        "OpenCore/Series-9/EFI/OC/Tools/CleanNvram.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ControlMsrE2.efi"      "OpenCore/Series-9/EFI/OC/Tools/ControlMsrE2.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/GopStop.efi"           "OpenCore/Series-9/EFI/OC/Tools/GopStop.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/KeyTester.efi"         "OpenCore/Series-9/EFI/OC/Tools/KeyTester.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/MmapDump.efi"          "OpenCore/Series-9/EFI/OC/Tools/MmapDump.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/OpenControl.efi"       "OpenCore/Series-9/EFI/OC/Tools/OpenControl.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/OpenShell.efi"         "OpenCore/Series-9/EFI/OC/Tools/OpenShell.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ResetSystem.efi"       "OpenCore/Series-9/EFI/OC/Tools/ResetSystem.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/RtcRw.efi"             "OpenCore/Series-9/EFI/OC/Tools/RtcRw.efi"
  cp -f "OpenCore/Update/EFI/OC/OpenCore.efi"                "OpenCore/Series-9/EFI/OC/OpenCore.efi"
fi

if [ -d "OpenCore/Series-100/EFI" ] && [ -d "OpenCore/Update/EFI" ]; then
  cp -f "OpenCore/Update/EFI/BOOT/BOOTx64.efi"               "OpenCore/Series-100/EFI/BOOT/BOOTx64.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/CrScreenshotDxe.efi" "OpenCore/Series-100/EFI/OC/Drivers/CrScreenshotDxe.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/NvmExpressDxe.efi"   "OpenCore/Series-100/EFI/OC/Drivers/NvmExpressDxe.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/OpenCanopy.efi"      "OpenCore/Series-100/EFI/OC/Drivers/OpenCanopy.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/OpenRuntime.efi"     "OpenCore/Series-100/EFI/OC/Drivers/OpenRuntime.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/BootKicker.efi"        "OpenCore/Series-100/EFI/OC/Tools/BootKicker.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ChipTune.efi"          "OpenCore/Series-100/EFI/OC/Tools/ChipTune.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/CleanNvram.efi"        "OpenCore/Series-100/EFI/OC/Tools/CleanNvram.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ControlMsrE2.efi"      "OpenCore/Series-100/EFI/OC/Tools/ControlMsrE2.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/GopStop.efi"           "OpenCore/Series-100/EFI/OC/Tools/GopStop.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/KeyTester.efi"         "OpenCore/Series-100/EFI/OC/Tools/KeyTester.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/MmapDump.efi"          "OpenCore/Series-100/EFI/OC/Tools/MmapDump.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/OpenControl.efi"       "OpenCore/Series-100/EFI/OC/Tools/OpenControl.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/OpenShell.efi"         "OpenCore/Series-100/EFI/OC/Tools/OpenShell.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ResetSystem.efi"       "OpenCore/Series-100/EFI/OC/Tools/ResetSystem.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/RtcRw.efi"             "OpenCore/Series-100/EFI/OC/Tools/RtcRw.efi"
  cp -f "OpenCore/Update/EFI/OC/OpenCore.efi"                "OpenCore/Series-100/EFI/OC/OpenCore.efi"
fi

if [ -d "OpenCore/Series-200/EFI" ] && [ -d "OpenCore/Update/EFI" ]; then
  cp -f "OpenCore/Update/EFI/BOOT/BOOTx64.efi"               "OpenCore/Series-200/EFI/BOOT/BOOTx64.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/CrScreenshotDxe.efi" "OpenCore/Series-200/EFI/OC/Drivers/CrScreenshotDxe.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/NvmExpressDxe.efi"   "OpenCore/Series-200/EFI/OC/Drivers/NvmExpressDxe.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/OpenCanopy.efi"      "OpenCore/Series-200/EFI/OC/Drivers/OpenCanopy.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/OpenRuntime.efi"     "OpenCore/Series-200/EFI/OC/Drivers/OpenRuntime.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/BootKicker.efi"        "OpenCore/Series-200/EFI/OC/Tools/BootKicker.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ChipTune.efi"          "OpenCore/Series-200/EFI/OC/Tools/ChipTune.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/CleanNvram.efi"        "OpenCore/Series-200/EFI/OC/Tools/CleanNvram.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ControlMsrE2.efi"      "OpenCore/Series-200/EFI/OC/Tools/ControlMsrE2.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/GopStop.efi"           "OpenCore/Series-200/EFI/OC/Tools/GopStop.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/KeyTester.efi"         "OpenCore/Series-200/EFI/OC/Tools/KeyTester.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/MmapDump.efi"          "OpenCore/Series-200/EFI/OC/Tools/MmapDump.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/OpenControl.efi"       "OpenCore/Series-200/EFI/OC/Tools/OpenControl.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/OpenShell.efi"         "OpenCore/Series-200/EFI/OC/Tools/OpenShell.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ResetSystem.efi"       "OpenCore/Series-200/EFI/OC/Tools/ResetSystem.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/RtcRw.efi"             "OpenCore/Series-200/EFI/OC/Tools/RtcRw.efi"
  cp -f "OpenCore/Update/EFI/OC/OpenCore.efi"                "OpenCore/Series-200/EFI/OC/OpenCore.efi"
fi

if [ -d "OpenCore/Series-300/EFI" ] && [ -d "OpenCore/Update/EFI" ]; then
  cp -f "OpenCore/Update/EFI/BOOT/BOOTx64.efi"               "OpenCore/Series-300/EFI/BOOT/BOOTx64.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/CrScreenshotDxe.efi" "OpenCore/Series-300/EFI/OC/Drivers/CrScreenshotDxe.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/NvmExpressDxe.efi"   "OpenCore/Series-300/EFI/OC/Drivers/NvmExpressDxe.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/OpenCanopy.efi"      "OpenCore/Series-300/EFI/OC/Drivers/OpenCanopy.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/OpenRuntime.efi"     "OpenCore/Series-300/EFI/OC/Drivers/OpenRuntime.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/BootKicker.efi"        "OpenCore/Series-300/EFI/OC/Tools/BootKicker.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ChipTune.efi"          "OpenCore/Series-300/EFI/OC/Tools/ChipTune.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/CleanNvram.efi"        "OpenCore/Series-300/EFI/OC/Tools/CleanNvram.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ControlMsrE2.efi"      "OpenCore/Series-300/EFI/OC/Tools/ControlMsrE2.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/GopStop.efi"           "OpenCore/Series-300/EFI/OC/Tools/GopStop.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/KeyTester.efi"         "OpenCore/Series-300/EFI/OC/Tools/KeyTester.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/MmapDump.efi"          "OpenCore/Series-300/EFI/OC/Tools/MmapDump.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/OpenControl.efi"       "OpenCore/Series-300/EFI/OC/Tools/OpenControl.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/OpenShell.efi"         "OpenCore/Series-300/EFI/OC/Tools/OpenShell.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ResetSystem.efi"       "OpenCore/Series-300/EFI/OC/Tools/ResetSystem.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/RtcRw.efi"             "OpenCore/Series-300/EFI/OC/Tools/RtcRw.efi"
  cp -f "OpenCore/Update/EFI/OC/OpenCore.efi"                "OpenCore/Series-300/EFI/OC/OpenCore.efi"
fi

if [ -d "OpenCore/Series-400/EFI" ] && [ -d "OpenCore/Update/EFI" ]; then
  cp -f "OpenCore/Update/EFI/BOOT/BOOTx64.efi"               "OpenCore/Series-400/EFI/BOOT/BOOTx64.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/CrScreenshotDxe.efi" "OpenCore/Series-400/EFI/OC/Drivers/CrScreenshotDxe.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/NvmExpressDxe.efi"   "OpenCore/Series-400/EFI/OC/Drivers/NvmExpressDxe.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/OpenCanopy.efi"      "OpenCore/Series-400/EFI/OC/Drivers/OpenCanopy.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/OpenRuntime.efi"     "OpenCore/Series-400/EFI/OC/Drivers/OpenRuntime.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/BootKicker.efi"        "OpenCore/Series-400/EFI/OC/Tools/BootKicker.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ChipTune.efi"          "OpenCore/Series-400/EFI/OC/Tools/ChipTune.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/CleanNvram.efi"        "OpenCore/Series-400/EFI/OC/Tools/CleanNvram.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ControlMsrE2.efi"      "OpenCore/Series-400/EFI/OC/Tools/ControlMsrE2.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/GopStop.efi"           "OpenCore/Series-400/EFI/OC/Tools/GopStop.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/KeyTester.efi"         "OpenCore/Series-400/EFI/OC/Tools/KeyTester.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/MmapDump.efi"          "OpenCore/Series-400/EFI/OC/Tools/MmapDump.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/OpenControl.efi"       "OpenCore/Series-400/EFI/OC/Tools/OpenControl.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/OpenShell.efi"         "OpenCore/Series-400/EFI/OC/Tools/OpenShell.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ResetSystem.efi"       "OpenCore/Series-400/EFI/OC/Tools/ResetSystem.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/RtcRw.efi"             "OpenCore/Series-400/EFI/OC/Tools/RtcRw.efi"
  cp -f "OpenCore/Update/EFI/OC/OpenCore.efi"                "OpenCore/Series-400/EFI/OC/OpenCore.efi"
fi

if [ -d "OpenCore/Series-500/EFI" ] && [ -d "OpenCore/Update/EFI" ]; then
  cp -f "OpenCore/Update/EFI/BOOT/BOOTx64.efi"               "OpenCore/Series-500/EFI/BOOT/BOOTx64.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/CrScreenshotDxe.efi" "OpenCore/Series-500/EFI/OC/Drivers/CrScreenshotDxe.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/NvmExpressDxe.efi"   "OpenCore/Series-500/EFI/OC/Drivers/NvmExpressDxe.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/OpenCanopy.efi"      "OpenCore/Series-500/EFI/OC/Drivers/OpenCanopy.efi"
  cp -f "OpenCore/Update/EFI/OC/Drivers/OpenRuntime.efi"     "OpenCore/Series-500/EFI/OC/Drivers/OpenRuntime.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/BootKicker.efi"        "OpenCore/Series-500/EFI/OC/Tools/BootKicker.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ChipTune.efi"          "OpenCore/Series-500/EFI/OC/Tools/ChipTune.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/CleanNvram.efi"        "OpenCore/Series-500/EFI/OC/Tools/CleanNvram.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ControlMsrE2.efi"      "OpenCore/Series-500/EFI/OC/Tools/ControlMsrE2.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/GopStop.efi"           "OpenCore/Series-500/EFI/OC/Tools/GopStop.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/KeyTester.efi"         "OpenCore/Series-500/EFI/OC/Tools/KeyTester.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/MmapDump.efi"          "OpenCore/Series-500/EFI/OC/Tools/MmapDump.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/OpenControl.efi"       "OpenCore/Series-500/EFI/OC/Tools/OpenControl.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/OpenShell.efi"         "OpenCore/Series-500/EFI/OC/Tools/OpenShell.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/ResetSystem.efi"       "OpenCore/Series-500/EFI/OC/Tools/ResetSystem.efi"
  cp -f "OpenCore/Update/EFI/OC/Tools/RtcRw.efi"             "OpenCore/Series-500/EFI/OC/Tools/RtcRw.efi"
  cp -f "OpenCore/Update/EFI/OC/OpenCore.efi"                "OpenCore/Series-500/EFI/OC/OpenCore.efi"
fi
