#!/bin/zsh

SOURCE="/Volumes/USB/Mac"
TARGET="/Volumes/USB/Mac"

mkdir -p $TARGET/${(C)USER}/Home

rsync -a $HOME/Documents $TARGET/${(C)USER}/Home/
rsync -a $HOME/Downloads $TARGET/${(C)USER}/Home/
rsync -a $HOME/Movies    $TARGET/${(C)USER}/Home/
rsync -a $HOME/Music     $TARGET/${(C)USER}/Home/
rsync -a $HOME/Pictures  $TARGET/${(C)USER}/Home/
