#!/bin/zsh

SOURCE="/Volumes/USB/Mac"

rsync -a $SOURCE/${(C)USER}/Home/Documents $HOME/
rsync -a $SOURCE/${(C)USER}/Home/Downloads $HOME/
rsync -a $SOURCE/${(C)USER}/Home/Movies    $HOME/
rsync -a $SOURCE/${(C)USER}/Home/Music     $HOME/
rsync -a $SOURCE/${(C)USER}/Home/Pictures  $HOME/
